Assignment 1: VectorTest.cpp File Reference
VectorTest.cpp File Reference
#include <iostream>
#include <string>
#include "Vector.h"
Typedefs
typedef Vector< int > IntVec
Functions
void Display (IntVec &Varray)
void Test01 (IntVec &Varray)
void Test02 (IntVec &Varray)
void Test03 (IntVec &Varray)
void Test04 (IntVec &Varray)
void Test05 (IntVec &Varray)
void Test06 (IntVec &Varray, int index)
void Test07 (IntVec &Varray, int element, int index)
void Test08 (IntVec &Varray)
void Test09 (IntVec &Varray, int element, int index)
int main ()
Typedef Documentation
IntVec
typedef Vector<int> IntVec
Definition at line 6 of file VectorTest.cpp.
Function Documentation
Display()
void Display (IntVec & Varray)
Definition at line 36 of file VectorTest.cpp.
 {
     cout << "No of Elements: " << Varray.Size() << endl;
     cout << "Capacity: " << Varray.GetCapacity() << endl;
     for(int i = 0; i < Varray.Size(); i++)
     {
         cout << "Element at [" << i << "] : " << Varray.At(i) << endl;
     }
     cout << endl;
 }
References Vector< T >::At(), Vector< T >::GetCapacity(), and Vector< T >::Size().
Referenced by Test01(), Test02(), Test03(), Test04(), Test05(), Test06(), Test07(), Test08(), and Test09().
main()
int main ()
Definition at line 19 of file VectorTest.cpp.
 {
     IntVec n1;
     Test01(n1);
     Test02(n1);
     Test03(n1);
     Test04(n1);
     Test05(n1);
     Test06(n1,2);
     Test07(n1,99,2);
     Test08(n1);
     Test09(n1,99,0);
     return 0;
 }
References Test01(), Test02(), Test03(), Test04(), Test05(), Test06(), Test07(), Test08(), and Test09().
Test01()
void Test01 (IntVec & Varray)
Definition at line 47 of file VectorTest.cpp.
 {
     cout << "=== Testing Default Constructor ===" << endl;
     cout << "Address: " << Varray.GetArray() << endl;
     Display(Varray);
 }
References Display(), and Vector< T >::GetArray().
Referenced by main().
Test02()
void Test02 (IntVec & Varray)
Definition at line 55 of file VectorTest.cpp.
 {
     cout << "=== Testing Add() ===" << endl;
     Varray.Add(10);
     Varray.Add(20);
     Varray.Add(30);
     Varray.Add(40);
     Varray.Add(50);
     Varray.Add(60);
     Display(Varray);
 }
References Vector< T >::Add(), and Display().
Referenced by main().
Test03()
void Test03 (IntVec & Varray)
Definition at line 68 of file VectorTest.cpp.
 {
     IntVec test(Varray);
     cout << "=== Testing Deep Copy Constructor ===" << endl;
     cout << "Address of array to be copied: " << Varray.GetArray() << endl;
     cout << "Address of array copied:       " << test.GetArray() << endl;
     Display(test);
 }
References Display(), and Vector< T >::GetArray().
Referenced by main().
Test04()
void Test04 (IntVec & Varray)
Definition at line 78 of file VectorTest.cpp.
 {
     cout << "=== Testing = Operator Deep Copy ===" << endl;
     IntVec test;
     test = Varray;
     cout << "Address of array to be copied: " << Varray.GetArray() << endl;
     cout << "Address of array copied:       " << test.GetArray() << endl;
     Display(test);
 }
References Display(), and Vector< T >::GetArray().
Referenced by main().
Test05()
void Test05 (IntVec & Varray)
Definition at line 91 of file VectorTest.cpp.
 {
     cout << "=== Testing Remove() ===" << endl;
     if(Varray.Remove())
     {
         cout << "Remove() is Successful" << endl;
         Display(Varray);
     }
     else
     {
         cout << "Remove() is NOT Successful" << endl << endl;
     }
 }
References Display(), and Vector< T >::Remove().
Referenced by main().
Test06()
void Test06 (IntVec & Varray, int index)
Definition at line 106 of file VectorTest.cpp.
 {
     cout << "=== Testing DeleteFrom() ===" << endl;
     if(Varray.DeleteFrom(index))
     {
         cout << "DeleteFrom() is Successful" << endl;
         Display(Varray);
     }
     else
     {
         cout << "DeleteFrom() is NOT Successful" << endl << endl;
     }
 }
References Vector< T >::DeleteFrom(), and Display().
Referenced by main().
Test07()
void Test07 (IntVec & Varray, int element, int index)
Definition at line 121 of file VectorTest.cpp.
 {
     cout << "=== Testing InsertAt() ===" << endl;
     if(Varray.InsertAt(element,index))
     {
         cout << "InsertAt() is Successful" << endl;
         Display(Varray);
     }
     else
     {
         cout << "InsertAt() is NOT Successful" << endl << endl;
     }
 }
References Display(), and Vector< T >::InsertAt().
Referenced by main().
Test08()
void Test08 (IntVec & Varray)
Definition at line 136 of file VectorTest.cpp.
 {
     cout << "=== Testing Empty() ===" << endl;
     Display(Varray);
     if(Varray.Empty())
     {
         cout << "Array is Empty" << endl << endl;
     }
     else
     {
         cout << "Array is NOT Empty" << endl << endl;
     }
 }
References Display(), and Vector< T >::Empty().
Referenced by main().
Test09()
void Test09 (IntVec & Varray, int element, int index)
Definition at line 150 of file VectorTest.cpp.
 {
     cout << "=== Testing ModifyAt() ===" << endl;
     if(Varray.ModifyAt(element,index))
     {
         cout << "ModifyAt() is Successful" << endl;
         Display(Varray);
     }
     else
     {
         cout << "ModifyAt() is NOT Successful" << endl << endl;
     }
 }
References Display(), and Vector< T >::ModifyAt().
Referenced by main().