Assignment 1: WindDataArrayTest.cpp File Reference
WindDataArrayTest.cpp File Reference
#include "WindDataArray.h"
Functions
void Test01 (WindDataArray &test)
void Test02 (WindDataArray &test)
void Test03 (WindDataArray &test)
void Test04 (WindDataArray &test)
void Test05 (WindDataArray &test)
void Test06 (WindDataArray &test)
int main ()
Function Documentation
main()
int main ()
Definition at line 10 of file WindDataArrayTest.cpp.
 {
     WindDataArray test;
     Test01(test);
     Test02(test);
     Test03(test);
     Test04(test);
     Test05(test);
     Test06(test);
     return 0;
 }
References Test01(), Test02(), Test03(), Test04(), Test05(), and Test06().
Test01()
void Test01 (WindDataArray & test)
Definition at line 25 of file WindDataArrayTest.cpp.
 {
     cout << "=== Testing ReadInputFileToStorage() ===" << endl;
     test.ReadInputFileToStorage("data/testsample_data.csv");
     for(int i = 0; i < test.Size(); i++)
     {
         WindData wd;
         test.Get(wd,i);
         cout << wd << endl;
     }
     cout << endl;
 }
References WindDataArray::Get(), WindDataArray::ReadInputFileToStorage(), and WindDataArray::Size().
Referenced by main().
Test02()
void Test02 (WindDataArray & test)
Definition at line 38 of file WindDataArrayTest.cpp.
 {
     cout << "=== Testing CalculateWindSpeedMean() ===" << endl;
     float mean = test.CalculateWindSpeedMean(3,2014);
     cout << "Speed Mean: " << mean << endl << endl;
 }
References WindDataArray::CalculateWindSpeedMean().
Referenced by main().
Test03()
void Test03 (WindDataArray & test)
Definition at line 46 of file WindDataArrayTest.cpp.
 {
     cout << "=== Testing CalculateWindSpeedSD() ===" << endl;
     float sd = test.CalculateWindSpeedSD(3,2014);
     cout << "Speed SD: " << sd << endl << endl;
 }
References WindDataArray::CalculateWindSpeedSD().
Referenced by main().
Test04()
void Test04 (WindDataArray & test)
Definition at line 53 of file WindDataArrayTest.cpp.
 {
     cout << "=== Testing CalculateAirTempMean() ===" << endl;
     float mean = test.CalculateAirTempMean(3,2014);
     cout << "Air Temp Mean: " << mean << endl << endl;
 }
References WindDataArray::CalculateAirTempMean().
Referenced by main().
Test05()
void Test05 (WindDataArray & test)
Definition at line 61 of file WindDataArrayTest.cpp.
 {
     cout << "=== Testing CalculateAirTempSD() ===" << endl;
     float sd = test.CalculateAirTempSD(3,2014);
     cout << "Air Temp SD: " << sd << endl << endl;
 }
References WindDataArray::CalculateAirTempSD().
Referenced by main().
Test06()
void Test06 (WindDataArray & test)
Definition at line 68 of file WindDataArrayTest.cpp.
 {
     cout << "=== Testing CalculateSolarRadTotal() ===" << endl;
     int sum = test.CalculateSolarRadTotal(3,2014);
     cout << "Solar Rad Total: " << sum << endl << endl;
 }
References WindDataArray::CalculateSolarRadTotal().
Referenced by main().