Assignment 1: WindDataArray Class Reference
WindDataArray Class Reference
#include <WindDataArray.h>
Public Member Functions
WindDataArray ()
void Get (WindData &element, int index)
int Size ()
void SetHeaderNames (string &line)
bool ReadInputFileToStorage (const string &fileName)
void StoreDateAndTime (WindData &wd, string &line, int currentColumn)
void StoreAirTemp (WindData &wd, string &line, int currentColumn)
void StoreSpeed (WindData &wd, string &line, int currentColumn)
void StoreSolarRad (WindData &wd, string &line, int currentColumn)
float CalculateWindSpeedMean (int month, int year)
float CalculateWindSpeedSD (int month, int year)
float CalculateAirTempMean (int month, int year)
float CalculateAirTempSD (int month, int year)
int CalculateSolarRadTotal (int month, int year)
Private Attributes
Vector< WindData > m_array
Vector< string > m_headerNames
Detailed Description
This class is used to store the wind data objects in a vector array, as well as the computational methods requiring the use of stored data
Definition at line 25 of file WindDataArray.h.
Constructor & Destructor Documentation
WindDataArray()
WindDataArray::WindDataArray ()
Default constructor
Definition at line 3 of file WindDataArray.cpp.
 {
 }
Member Function Documentation
CalculateAirTempMean()
float WindDataArray::CalculateAirTempMean (int month, int year)
This method is used to calculate the average air temperature of given month and year
Parameters
month - Month to be calculated
year - Year to be calculated
Returns
mean - Average air temperature
Definition at line 168 of file WindDataArray.cpp.
 {
     float sum;
     float counter;
     for(int i = 0; i < Size(); i++)
     {
         WindData wd;
         wd = m_array.At(i);
         Date d;
         wd.GetDate(d);
         if(d.GetYear() == year)
         {
             if(d.GetMonth() == month)
             {
                 sum += wd.GetAirTemp();
                 counter++;
             }
         }
     }
     float mean = sum / counter;
     if(mean == 0)
     {
         return 0;
     }
     else
     {
         return mean;
     }
 }
References Vector< T >::At(), WindData::GetAirTemp(), WindData::GetDate(), Date::GetMonth(), Date::GetYear(), m_array, and Size().
Referenced by CalculateAirTempSD(), CheckDataExistInMonth(), CheckDataExistInYear(), Menu2(), PrintDataToFile(), and Test04().
CalculateAirTempSD()
float WindDataArray::CalculateAirTempSD (int month, int year)
This method is used to calculate the standard deviation of air temperature of given month and year
Parameters
month - Month to be calculated
year - Year to be calculated
Returns
sd - Air temperature standard deviation
Definition at line 199 of file WindDataArray.cpp.
 {
     float mean = CalculateAirTempMean(month,year);
     float sum;
     float counter;
     for(int i = 0; i < Size(); i++)
     {
         WindData wd;
         wd = m_array.At(i);
         Date d;
         wd.GetDate(d);
         if(d.GetYear() == year)
         {
             if(d.GetMonth() == month)
             {
                 sum += (wd.GetAirTemp() - mean)*(wd.GetAirTemp() - mean);
                 counter++;
             }
         }
     }
     sum = sum / counter;
     sqrt(sum);
     if(sum == 0)
     {
         return 0;
     }
     else
     {
         return sum;
     }
 }
References Vector< T >::At(), CalculateAirTempMean(), WindData::GetAirTemp(), WindData::GetDate(), Date::GetMonth(), Date::GetYear(), m_array, and Size().
Referenced by Menu2(), PrintDataToFile(), and Test05().
CalculateSolarRadTotal()
int WindDataArray::CalculateSolarRadTotal (int month, int year)
This method is used to calculate the total solar radiation of given month and year
Parameters
month - Month to be calculated
year - Year to be calculated
Returns
sum - Total solar radiation
Definition at line 233 of file WindDataArray.cpp.
 {
     int sum;
     for(int i = 0; i < Size(); i++)
     {
         WindData wd;
         wd = m_array.At(i);
         Date d;
         wd.GetDate(d);
         if(d.GetYear() == year)
         {
             if(d.GetMonth() == month)
             {
                 sum += wd.GetSolarRad();
             }
         }
     }
     return sum;
 }
References Vector< T >::At(), WindData::GetDate(), Date::GetMonth(), WindData::GetSolarRad(), Date::GetYear(), m_array, and Size().
Referenced by CheckDataExistInMonth(), CheckDataExistInYear(), Menu3(), PrintDataToFile(), and Test06().
CalculateWindSpeedMean()
float WindDataArray::CalculateWindSpeedMean (int month, int year)
This method is used to calculate the average wind speed of given month and year
Parameters
month - Month to be calculated
year - Year to be calculated
Returns
mean - Average wind speed
Definition at line 102 of file WindDataArray.cpp.
 {
     float sum;
     float counter;
     for(int i = 0; i < Size(); i++)
     {
         WindData wd;
         wd = m_array.At(i);
         Date d;
         wd.GetDate(d);
         if(d.GetYear() == year) // run through every year to find right year
         {
             if(d.GetMonth() == month)
             {
                 sum += wd.GetSpeed();
                 counter++;
             }
         }
     }
     float mean = sum / counter;
     if(mean == 0)
     {
         return 0;
     }
     else
     {
         return mean;
     }
 }
References Vector< T >::At(), WindData::GetDate(), Date::GetMonth(), WindData::GetSpeed(), Date::GetYear(), m_array, and Size().
Referenced by CalculateWindSpeedSD(), CheckDataExistInMonth(), CheckDataExistInYear(), Menu1(), PrintDataToFile(), and Test02().
CalculateWindSpeedSD()
float WindDataArray::CalculateWindSpeedSD (int month, int year)
This method is used to calculate the standard deviation of wind speed of given month and year
Parameters
month - Month to be calculated
year - Year to be calculated
Returns
sd - Wind speed standard deviation
Definition at line 134 of file WindDataArray.cpp.
 {
     float mean = CalculateWindSpeedMean(month,year);
     float sum;
     float counter;
     for(int i = 0; i < Size(); i++)
     {
         WindData wd;
         wd = m_array.At(i);
         Date d;
         wd.GetDate(d);
         if(d.GetYear() == year)
         {
             if(d.GetMonth() == month)
             {
                 sum += (wd.GetSpeed() - mean)*(wd.GetSpeed() - mean);
                 counter++;
             }
         }
     }
     sum = sum / counter;
     sqrt(sum);
     if(sum == 0)
     {
         return 0;
     }
     else
     {
         return sum;
     }
 }
References Vector< T >::At(), CalculateWindSpeedMean(), WindData::GetDate(), Date::GetMonth(), WindData::GetSpeed(), Date::GetYear(), m_array, and Size().
Referenced by Menu1(), PrintDataToFile(), and Test03().
Get()
void WindDataArray::Get (WindData & element, int index)
This method is used to retrieve a WindData object from the vector array, from a specified index position
Parameters
element - WindData object to be retrieved, passed via reference
index - Position of element in the array to be retrieved
Definition at line 8 of file WindDataArray.cpp.
 {
     element = m_array.At(index);
 }
References Vector< T >::At(), and m_array.
Referenced by Test01().
ReadInputFileToStorage()
bool WindDataArray::ReadInputFileToStorage (const string & fileName)
This method is used to read a csv file and extract the required information within. This method is to be used with the appropriate data type storage methods.
Parameters
fileName - Name of data file
Returns
boolean - Return true if operation is successful, otherwise false.
Definition at line 18 of file WindDataArray.cpp.
 {
     ifstream infile(fileName);
     if( !infile ) return false;
     string line;
     getline(infile,line); // get header column names
     SetHeaderNames(line);
     while(getline(infile,line))
     {
         WindData wd;
         istringstream iss(line); // initialize row into stream format to be used for processing data into individual columns
         string ssline;
         int currentColumn = 0; // first column starts at 0
         while(getline(iss,ssline,','))
         {
             // runs through every storage column, when matching column found, store data into right storage
             StoreDateAndTime(wd,ssline,currentColumn);
             StoreAirTemp(wd,ssline,currentColumn);
             StoreSpeed(wd,ssline,currentColumn);
             StoreSolarRad(wd,ssline,currentColumn);
             currentColumn++;
         }
         m_array.Add(wd);
     }
     infile.close();
     return true;
 }
References Vector< T >::Add(), m_array, SetHeaderNames(), StoreAirTemp(), StoreDateAndTime(), StoreSolarRad(), and StoreSpeed().
Referenced by StoreDataToArray(), and Test01().
SetHeaderNames()
void WindDataArray::SetHeaderNames (string & line)
This method is used to find the header names from the input csv files, to be used for identifying the columns in the csv file for processing data storage.
Parameters
line - Header row from csv file as a string
Definition at line 93 of file WindDataArray.cpp.
 {
     istringstream iss(line);
     while(getline(iss,line,','))
     {
         m_headerNames.Add(line);
     }
 }
References Vector< T >::Add(), and m_headerNames.
Referenced by ReadInputFileToStorage().
Size()
int WindDataArray::Size ()
This method is used to find the number of elements in the array.
Returns
size - Number of elements in the array
Definition at line 13 of file WindDataArray.cpp.
 {
     return m_array.Size();
 }
References m_array, and Vector< T >::Size().
Referenced by CalculateAirTempMean(), CalculateAirTempSD(), CalculateSolarRadTotal(), CalculateWindSpeedMean(), CalculateWindSpeedSD(), and Test01().
StoreAirTemp()
void WindDataArray::StoreAirTemp (WindData & wd, string & line, int currentColumn)
This method is used to store the air temperature into the WindData object
Parameters
wd - WindData object to store at
line - String of data to store
currentColumn - Used to indicate the current data in line
Definition at line 65 of file WindDataArray.cpp.
 {
     string name = m_headerNames.At(currentColumn);
     if(name.compare("T") == 0)
     {
         wd.SetAirTemp(stof(line));
     }
 }
References Vector< T >::At(), m_headerNames, and WindData::SetAirTemp().
Referenced by ReadInputFileToStorage().
StoreDateAndTime()
void WindDataArray::StoreDateAndTime (WindData & wd, string & line, int currentColumn)
This method is used to store the date and time into the WindData object
Parameters
wd - WindData object to store at
line - String of data to store
currentColumn - Used to indicate the current data in line
Definition at line 49 of file WindDataArray.cpp.
 {
     string name = m_headerNames.At(currentColumn);
     if(name.compare("WAST") == 0)
     {
         Date d;
         Time t;
         istringstream iss(line);
         iss >> d >> t;
         wd.SetDate(d);
         wd.SetTime(t);
     }
 }
References Vector< T >::At(), m_headerNames, WindData::SetDate(), and WindData::SetTime().
Referenced by ReadInputFileToStorage().
StoreSolarRad()
void WindDataArray::StoreSolarRad (WindData & wd, string & line, int currentColumn)
This method is used to store the solar radiation into the WindData object
Parameters
wd - WindData object to store at
line - String of data to store
currentColumn - Used to indicate the current data in line
Definition at line 84 of file WindDataArray.cpp.
 {
     string name = m_headerNames.At(currentColumn);
     if(name.compare("SR") == 0)
     {
         wd.SetSolarRad(stoi(line));
     }
 }
References Vector< T >::At(), m_headerNames, and WindData::SetSolarRad().
Referenced by ReadInputFileToStorage().
StoreSpeed()
void WindDataArray::StoreSpeed (WindData & wd, string & line, int currentColumn)
This method is used to store the wind speed into the WindData object
Parameters
wd - WindData object to store at
line - String of data to store
currentColumn - Used to indicate the current data in line
Definition at line 75 of file WindDataArray.cpp.
 {
     string name = m_headerNames.At(currentColumn);
     if(name.compare("S") == 0)
     {
         wd.SetSpeed(stof(line));
     }
 }
References Vector< T >::At(), m_headerNames, and WindData::SetSpeed().
Referenced by ReadInputFileToStorage().
Member Data Documentation
m_array
Vector<WindData> WindDataArray::m_array private
Used to store the wind data objects in a vector array
Definition at line 31 of file WindDataArray.h.
Referenced by CalculateAirTempMean(), CalculateAirTempSD(), CalculateSolarRadTotal(), CalculateWindSpeedMean(), CalculateWindSpeedSD(), Get(), ReadInputFileToStorage(), and Size().
m_headerNames
Vector<string> WindDataArray::m_headerNames private
For indicating the csv data retrieved by its columns. To be used for storage of data into appropriate WindData attributes
Definition at line 37 of file WindDataArray.h.
Referenced by SetHeaderNames(), StoreAirTemp(), StoreDateAndTime(), StoreSolarRad(), and StoreSpeed().
The documentation for this class was generated from the following files:
WindDataArray.h
WindDataArray.cpp