Assignment 1: Vector< T > Class Template Reference
Vector< T > Class Template Reference
#include <Vector.h>
Public Member Functions
Vector ()
~Vector ()
Vector (Vector &anotherArray)
Vector< T > & operator= (Vector &anotherArray)
bool Add (T element)
bool Remove ()
bool InsertAt (T element, int index)
bool DeleteFrom (int index)
int Size ()
T & At (int index)
bool Empty ()
bool ModifyAt (T element, int index)
T * GetArray ()
int GetCapacity ()
Private Attributes
T * m_array
int m_numElements
int m_capacity
Detailed Description
template<class T>
class Vector< T >
This class is a template classic Vector class to be used with other projects
Definition at line 17 of file Vector.h.
Constructor & Destructor Documentation
Vector() [1/2]
template<class T > Vector< T >::Vector
Default constructor to initialize a vector
Definition at line 140 of file Vector.h.
 {
     // initialize an array of size INITIAL_SIZE
     m_numElements = 0;
     m_capacity = 0;
     // try to create array
     m_array = new T[INITIAL_SIZE];
     if(m_array != nullptr)
     {
         m_capacity = INITIAL_SIZE;
     }
 }
~Vector()
template<class T > Vector< T >::~Vector
Default deconstructor to delete the array and change array pointer to nullptr
Definition at line 154 of file Vector.h.
 {
     if(m_array != nullptr)
     {
         delete[] m_array;
         m_array = nullptr;
     }
 }
Vector() [2/2]
template<class T > Vector< T >::Vector (Vector< T > & anotherArray)
Constructor to initialize using another vector
Parameters
anotherArray - Vector to be used for initialization
Definition at line 218 of file Vector.h.
 {
     m_numElements = 0;
     m_capacity = 0;
     // try to create array
     m_array = new T[INITIAL_SIZE];
     if(m_array != nullptr)
     {
         m_capacity = INITIAL_SIZE;
         for(int i = 0; i < anotherArray.Size(); i++)
         {
             T tempElement = anotherArray.At(i);
             Add(tempElement);
         }
     }
 }
Member Function Documentation
Add()
template<class T > bool Vector< T >::Add (T element)
Method used to add an element into the end of the array
Parameters
element - Element to be added
Returns
boolean - True if operation is successful, otherwise false
Definition at line 164 of file Vector.h.
 {
     if(m_numElements >= m_capacity)
     {
         int newCapacity = m_capacity * 2;
         T *tempArray = new T[newCapacity];
         //if tempArray is successfully allocated
         if(tempArray != nullptr)
         {
             // copy all elements from old array to new array
             for(int i = 0; i < m_numElements; i++)
             {
                 tempArray[i] = m_array[i];
             }
             delete[] m_array;
             m_array = tempArray;
             tempArray = nullptr;
             m_capacity = newCapacity;
             // add the new item into the array
             m_array[m_numElements] = element;
             m_numElements++;
             return true;
         }
         else
         {
             return false;
         }
     }
     else
     {
         // add the new item into the array
         m_array[m_numElements] = element;
         m_numElements++;
         return true;
     }
 }
Referenced by WindDataArray::ReadInputFileToStorage(), WindDataArray::SetHeaderNames(), and Test02().
At()
template<class T > T & Vector< T >::At (int index)
Method used to retrieve element at a position according to the index
Parameters
index - Position in the array for element to be retrieved
Returns
element - Element in the position
Definition at line 212 of file Vector.h.
 {
     return *(m_array + index);
 }
Referenced by WindDataArray::CalculateAirTempMean(), WindDataArray::CalculateAirTempSD(), WindDataArray::CalculateSolarRadTotal(), WindDataArray::CalculateWindSpeedMean(), WindDataArray::CalculateWindSpeedSD(), Display(), WindDataArray::Get(), Vector< WindData >::operator=(), WindDataArray::StoreAirTemp(), WindDataArray::StoreDateAndTime(), WindDataArray::StoreSolarRad(), WindDataArray::StoreSpeed(), and Vector< WindData >::Vector().
DeleteFrom()
template<class T > bool Vector< T >::DeleteFrom (int index)
Method used to remove an element at a position according to the index
Parameters
element - Element to be removed
index - Position in the array for element to be removed
Returns
boolean - True if operation is successful, otherwise false
Definition at line 266 of file Vector.h.
 {
     if(index < m_numElements && index >= 0)
     {
         for(int i = index; i < m_numElements; i++)
         {
             *(m_array + i) = *(m_array + i + 1);
         }
         m_numElements--;
         return true;
     }
     else
     {
         return false;
     }
 }
Referenced by Test06().
Empty()
template<class T > bool Vector< T >::Empty
Method used to check if the array is empty
Returns
boolean - True if empty, otherwise false
Definition at line 333 of file Vector.h.
 {
     if(m_array != nullptr)
     {
         if(m_numElements == 0)
         {
             return true;
         }
     }
     return false;
 }
Referenced by Test08().
GetArray()
template<class T > T * Vector< T >::GetArray
Get method for m_array
Returns
m_array - Object's m_array
Definition at line 134 of file Vector.h.
 {
     return m_array;
 }
Referenced by Test01(), Test03(), and Test04().
GetCapacity()
template<class T > int Vector< T >::GetCapacity
Get method for m_capacity
Returns
m_capacity - Object's m_capacity
Definition at line 128 of file Vector.h.
 {
     return m_capacity;
 }
Referenced by Display().
InsertAt()
template<class T > bool Vector< T >::InsertAt (T element, int index)
Method used to add an element at a position according to the index
Parameters
element - Element to be added
index - Position in the array for element to be added
Returns
boolean - True if operation is successful, otherwise false
Definition at line 284 of file Vector.h.
 {
     if(index < m_numElements && index >= 0)
     {
         if(m_numElements >= m_capacity)
         {
             int newCapacity = m_capacity * 2;
             T *tempArray = new T[newCapacity];
             //if tempArray is successfully allocated
             if(tempArray != nullptr)
             {
                 // copy all elements from old array to new array
                 for(int i = 0; i < m_numElements; i++)
                 {
                     tempArray[i] = m_array[i];
                 }
                 delete[] m_array;
                 m_array = tempArray;
                 tempArray = nullptr;
                 m_capacity = newCapacity;
                 for(int i = m_numElements; i > index; i--) // move elements backwards, starting from
                 {
                     *(m_array + i) = *(m_array + i - 1);
                 }
                 *(m_array + index) = element;
                 m_numElements++;
                 return true;
             }
         }
         else
         {
             for(int i = m_numElements; i > index; i--)
             {
                 *(m_array + i) = *(m_array + i - 1);
             }
             *(m_array + index) = element;
             m_numElements++;
             return true;
         }
     }
     else
     {
         return false;
     }
 }
Referenced by Test07().
ModifyAt()
template<class T > bool Vector< T >::ModifyAt (T element, int index)
Method used to change element at a position according to the index
Parameters
element - Element to be changed
index - Position in the array for element to be changed
Returns
boolean - True if operation is successful, otherwise false
Definition at line 346 of file Vector.h.
 {
     if(m_array != nullptr)
     {
         if(index < m_numElements && index >= 0)
         {
             *(m_array + index) = element;
             return true;
         }
     }
     return false;
 }
Referenced by Test09().
operator=()
template<class T > Vector< T > & Vector< T >::operator= (Vector< T > & anotherArray)
Overloaded = operator used for deep copying
Parameters
anotherArray - Vector to be used for copying
Definition at line 236 of file Vector.h.
 {
     if(m_array != nullptr)
     {
         for(int i = 0; i < anotherArray.Size(); i++)
         {
             T tempElement = anotherArray.At(i);
             Add(tempElement);
         }
     }
     return *this;
 }
Remove()
template<class T > bool Vector< T >::Remove
Method used to remove an element at the end of the array
Returns
boolean - True if operation is successful, otherwise false
Definition at line 252 of file Vector.h.
 {
     if(m_numElements > 0)
     {
         m_numElements--;
         return true;
     }
     else
     {
         return false;
     }
 }
Referenced by Test05().
Size()
template<class T > int Vector< T >::Size
Method used to find the size of the array
Returns
m_numElements - Number of elements in the array
Definition at line 206 of file Vector.h.
 {
     return m_numElements;
 }
Referenced by Display(), Vector< WindData >::operator=(), WindDataArray::Size(), and Vector< WindData >::Vector().
Member Data Documentation
m_array
template<class T > T* Vector< T >::m_array private
Pointer to the array/vector
Definition at line 23 of file Vector.h.
m_capacity
template<class T > int Vector< T >::m_capacity private
Size of the array
Definition at line 33 of file Vector.h.
m_numElements
template<class T > int Vector< T >::m_numElements private
Number of elements in the array
Definition at line 28 of file Vector.h.
The documentation for this class was generated from the following file:
Vector.h